# Generated by Django 5.2.6 on 2025-09-30 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0004_alter_product_image_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.retailer')),
            ],
        ),
    ]
