# Generated by Django 5.2.6 on 2025-10-03 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_alter_product_farmer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.farmer'),
        ),
    ]
