# Generated by Django 5.2.6 on 2025-10-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_alter_farmer_name_alter_product_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
