# Generated by Django 5.2.6 on 2025-10-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0013_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_farmer', to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_retailer', to='projectapp.retailer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_farmer', to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_retailer', to='projectapp.retailer'),
        ),
    ]
