# Generated by Django 5.2.6 on 2025-11-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0016_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
