# Generated by Django 5.2.6 on 2025-11-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0017_order_address_order_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailer',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
