# Generated by Django 5.2.6 on 2025-11-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0018_farmer_is_trained_retailer_is_trained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='is_trained',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='is_trained',
        ),
        migrations.AddField(
            model_name='farmer',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='contact',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='gender',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
