# Generated by Django 5.2.6 on 2025-11-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0019_remove_farmer_is_trained_remove_retailer_is_trained_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='profile_image',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='retailer',
            name='profile_image',
            field=models.ImageField(default='profiles/default.jpg', upload_to='profiles/'),
        ),
    ]
