# Generated by Django 5.2.6 on 2025-11-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0022_alter_farmer_password_alter_retailer_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver_farmer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='receiver_retailer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender_farmer',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender_retailer',
        ),
        migrations.RemoveField(
            model_name='retailer',
            name='user',
        ),
        migrations.AddField(
            model_name='notification',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='projectapp.farmer'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
