# Generated by Django 5.2.6 on 2025-11-23 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0023_remove_farmer_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='projectapp.farmer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to='projectapp.retailer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='projectapp.farmer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to='projectapp.retailer'),
        ),
    ]
