# Generated by Django 5.2.6 on 2025-11-23 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0024_remove_notification_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='projectapp.retailer'),
        ),
    ]
