# Generated by Django 5.2.6 on 2025-11-24 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0025_alter_notification_sender_farmer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=128)),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('auto', 'Auto'), ('tempo', 'Tempo'), ('pickup', 'Pickup'), ('truck', 'Truck')], default='tempo', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, max_length=50, null=True)),
                ('capacity_kg', models.IntegerField(default=1000)),
                ('rate_per_km', models.FloatField(default=12.0)),
                ('is_available', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('driver_photo', models.ImageField(blank=True, null=True, upload_to='drivers/')),
                ('license_doc', models.FileField(blank=True, null=True, upload_to='drivers/docs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(default=0.0)),
                ('delivery_charge', models.FloatField(default=0.0)),
                ('driver_earning', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('picked', 'Picked'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='projectapp.order')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='projectapp.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DriverNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projectapp.driver')),
            ],
        ),
    ]
