# Generated by Django 5.2.6 on 2025-11-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0028_chatmessage_document_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_for',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('doc', 'Document'), ('voice', 'Voice'), ('location', 'Location'), ('sticker', 'Sticker')], default='text', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='starred_by',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='chat_voice/'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_farmer', to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages_retailer', to='projectapp.retailer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_farmer', to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages_retailer', to='projectapp.retailer'),
        ),
    ]
