# Generated by Django 5.2.6 on 2025-11-25 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0029_chatmessage_deleted_for_chatmessage_is_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='receiver_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications_driver', to='projectapp.driver'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications_driver', to='projectapp.driver'),
        ),
    ]
