# Generated by Django 5.2.6 on 2025-11-25 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0030_notification_receiver_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_notifications', to='projectapp.driver'),
        ),
    ]
