# Generated by Django 5.2.6 on 2025-11-26 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0031_alter_delivery_assigned_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='deleted_for',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='location',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='starred_by',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projectapp.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('doc', 'Document'), ('voice', 'Voice')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recv_f', to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='receiver_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recv_r', to='projectapp.retailer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='sender_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.retailer'),
        ),
    ]
