# Generated by Django 5.2.6 on 2025-11-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0032_remove_chatmessage_deleted_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='document',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_farmer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver_retailer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='voice',
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
