# Generated by Django 5.2.6 on 2025-11-26 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0033_remove_chatmessage_document_remove_chatmessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='projectapp.order'),
        ),
    ]
