# Generated by Django 5.2.6 on 2025-11-26 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0034_alter_chatmessage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_farmer',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_retailer',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_type',
            field=models.CharField(default='farmer', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='projectapp.order'),
        ),
    ]
