# Generated by Django 5.2.6 on 2025-11-26 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0035_remove_chatmessage_sender_farmer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender_type',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.farmer'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sender_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projectapp.retailer'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.order'),
        ),
    ]
