# Generated by Django 5.2.6 on 2025-11-26 08:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0036_remove_chatmessage_sender_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='sender_driver',
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='projectapp.driver'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='projectapp.retailer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender_farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.farmer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender_retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.retailer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
