# Generated by Django 5.2.6 on 2025-11-27 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0037_remove_notification_sender_driver_notification_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_verified', models.BooleanField(default=False)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='drivers/vehicle_photos/')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='projectapp.driver')),
            ],
        ),
    ]
