# Generated by Django 5.2.6 on 2025-11-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0038_driverprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='license_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_photo',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/vehicle_photos/'),
        ),
        migrations.DeleteModel(
            name='DriverProfile',
        ),
    ]
