# Generated by Django 5.2.6 on 2025-11-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0039_driver_license_expiry_date_driver_license_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='is_paid_out',
            field=models.BooleanField(default=False),
        ),
    ]
