# Generated by Django 5.2.6 on 2025-11-29 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0041_retailer_city_retailer_gst_number_retailer_pincode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
