# Generated by Django 5.2.6 on 2025-12-03 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0042_retailer_email_otp_retailer_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('profit', models.FloatField()),
                ('date', models.DateTimeField()),
                ('quantity', models.FloatField(default=1)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.product')),
            ],
        ),
    ]
