# Generated by Django 5.2.6 on 2025-12-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0044_alter_sale_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered'), ('Paid', 'Paid')], default='Pending', max_length=30),
        ),
    ]
