# Generated by Django 5.2.6 on 2026-01-12 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0046_samplerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplerequest',
            name='quantity',
            field=models.FloatField(default=2, help_text='Sample quantity in kg'),
        ),
        migrations.CreateModel(
            name='RetailerSampleReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('review', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.retailer')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.samplerequest')),
            ],
            options={
                'unique_together': {('sample', 'retailer')},
            },
        ),
    ]
