# Generated by Django 6.0.2 on 2026-02-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0047_alter_samplerequest_quantity_retailersamplereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='farmer_paid',
            field=models.BooleanField(default=False),
        ),
    ]
