# Generated by Django 6.0.2 on 2026-02-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0049_farmer_account_holder_name_farmer_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farmer_paid',
            field=models.BooleanField(default=False),
        ),
    ]
