# Generated by Django 6.0.2 on 2026-02-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0050_farmer_farmer_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='account_holder_name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='farmer_paid',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='ifsc_code',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='upi_id',
        ),
    ]
