# Generated by Django 6.0.2 on 2026-02-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0052_alter_delivery_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
