# Generated by Django 6.0.2 on 2026-02-15 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0054_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.product')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.retailer')),
            ],
        ),
    ]
