# Generated by Django 6.0.2 on 2026-02-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0056_alter_order_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
