# Generated by Django 6.0.2 on 2026-03-03 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0057_farmer_bank_account_number_farmer_ifsc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch_deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('collecting', 'Collecting Orders'), ('ready', 'Ready For Dispatch'), ('dispatched', 'Dispatched'), ('completed', 'Completed')], default='collecting', max_length=20)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectapp.driver')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.farmer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='projectapp.trip'),
        ),
    ]
