# Generated by Django 6.0.2 on 2026-03-03 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0058_farmer_latitude_farmer_longitude_trip_order_trip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='longitude',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
