# Generated by Django 6.0.2 on 2026-03-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0060_driver_latitude_driver_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
