# Generated by Django 6.0.2 on 2026-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0061_farmer_latitude_farmer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='waiting_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
