# Generated by Django 6.0.2 on 2026-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0062_driver_waiting_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='longitude',
        ),
        migrations.AddField(
            model_name='product',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
