# Generated by Django 6.0.2 on 2026-03-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0063_remove_farmer_latitude_remove_farmer_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
