# Generated by Django 6.0.2 on 2026-03-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0064_retailer_latitude_retailer_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplerequest',
            name='charge_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='charge_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='samplerequest',
            name='sample_charge',
            field=models.FloatField(default=50.0),
        ),
        migrations.AlterField(
            model_name='samplerequest',
            name='quantity',
            field=models.FloatField(choices=[(1.0, '1 kg'), (2.0, '2 kg'), (5.0, '5 kg')], default=2),
        ),
        migrations.AlterField(
            model_name='samplerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('picked', 'Picked'), ('delivered', 'Delivered'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
